micronaut:
  application:
    name: "Phone Formatter Function"
  server:
    port: ${PORT:8080}
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
    intercept-url-map:
      - pattern: /openapi/**
        http-method: GET
        access:
          - isAnonymous()
    basic-auth:
      enabled: false
    endpoints:
      login:
        enabled: false
      logout:
        enabled: false
      oauth:
        enabled: false
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /openapi/**
application:
  admin:
    identity: admin
    secret: ${ADMIN_PASSWORD:secret}
    roles:
      - ADMIN
  test:
    identity: qa
    secret: ${TEST_PASSWORD:secret}
    roles: []
