name: Deploy new version to RapidAPI
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: List
        run: ls
      - name: Deploy
        uses: wei/curl@master
        with:
          args: "--request PUT --url https://openapi-provisioning.p.rapidapi.com/v1/apis/${{ secrets.API_ID }} --header 'content-type: multipart/form-data' --header 'x-rapidapi-host: openapi-provisioning.p.rapidapi.com' --header 'x-rapidapi-key: ${{ secrets.API_KEY }}' --form file=@file"
