name: Deploy new version to RapidAPI
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: wei/curl@master
        with:
          args: >
            --request PUT
            --url https://rapidapi.p.rapidapi.com/v1/apis/${{ secrets.API_ID }}
            --header 'content-type: application/x-www-form-urlencoded'
            --header 'x-rapidapi-host: openapi-provisioning.p.rapidapi.com'
            --header 'x-rapidapi-key: ${{ secrets.API_KEY }}'
            --form 'file=/github/workspace/build/classes/java/main/META-INF/swagger/phone-formatter-1.0.yml'
